### ISSUE TITLE
Remove deprecated +r mode for 2.12 release

### ISSUE THREAD

**Issue by wilhelmy** [ircnet/ircd#1]
old crap be gone!

`+R *!*@*` is a better way to accomplish the same.

**Comment by janicez** [comment]
Maybe keep +r, and have it set +R *!*@* and then unset itself? That's what I'd do if it was my program. At least, that's the sort of way Freenode's ircd-seven implements unrelated channel mode +R (meaning, registered-only speech) - by setting +q $~a (on seven, q is not a flag mode but a list mode like +beIR (but +R doesn't exist on seven because it's expected to be used with a Services program). meaning: ban from speaking all who do not match extended ban "a" without an argument - which on charybdis networks like Freenode is everyone who is not registered with nickserv) - yes I know IRCd The Original Code does not have extbans or even a concept of registration, but I thought the comparison was appropriate.
